import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header/Header";
import Footer from "./_components/Footer";
import HeaderMobile from "./_components/Header/HeaderMobile";
import BottomMenu from "./_components/MobileComponents/BottomMenu";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Crave Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          "antialiased min-h-screen flex flex-col",
        )}
      >
        <div className="lg:hidden">
          <HeaderMobile />
        </div>
        <div className="block md:hidden">
          <Header />
        </div>

        <main className="flex-1 pb-16 lg:pb-0">{children}</main>

        <BottomMenu className="lg:hidden" />
        <div className="block">
          <Footer />
        </div>
      </body>
    </html>
  );
}
